# Sync any changes to this *other than where explicitly specified* with the copy
# in `nostarch/book.toml`!

[book]
title = "The Rust Programming Language"
authors = ["Steve Klabnik", "Carol Nichols", "Contributions from the Rust Community"]

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css", "theme/semantic-notes.css", "theme/listing.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/rust-lang/book"

[output.pandoc]
additional-css = ["ferris.css", "theme/2018-edition.css", "theme/semantic-notes.css", "theme/listing.css"]
additional-js = ["ferris.js"]
hosted-html = "https://doc.rust-lang.org/book"

[output.pandoc.code]
show-hidden-lines = true

[output.pandoc.profile.epub]
output-file = "The Rust Programming Language.epub"
to = "epub"
from = "commonmark"
file-scope = true
number-sections = true
standalone = true
table-of-contents = false

[output.pandoc.profile.epub.variables]
epub-cover-image = "cover.jpg"

# Do not sync this preprocessor; it is for the HTML renderer only.
[preprocessor.trpl-note]

[preprocessor.trpl-listing]
output-mode = "default"

[rust]
edition = "2021"
